name: Decompile Sonic 3 HD

on:
  workflow_dispatch:

jobs:
  decompile:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # Using .NET 8 as it has broader global tool compatibility

      # Install a deobfuscator tool
      - name: Install de4dot
        run: dotnet tool install --global de4dot

      - name: Install ILSpy CLI
        run: dotnet tool install --global ilspycmd

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Deobfuscate Executable
        run: |
          mkdir -p cleaned
          # de4dot will analyze the file, unpack it, and rename bad characters to "Class0", "Method0", etc.
          de4dot "original/Sonic 3 HD Tech Demo.exe" -o "cleaned/sonic3hd_clean.exe"

      - name: Decompile Sonic 3 HD
        run: |
          mkdir -p src
          ilspycmd \
            -p \
            --nested-directories \
            -o src \
            "cleaned/sonic3hd_clean.exe"

      - name: Commit and Push Source Code
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          
          git add src/
          
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "chore: deobfuscate and decompile src folder"
            git push origin HEAD:${{ github.ref_name }}
          fi
